name: eso
description: 亦搜，亦看，亦闻
publish_to: none
version: 1.21.13+12113
homepage: https://github.com/mabdc/eso
author: mabdc

environment:
  sdk: ">=2.7.0 <3.2.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  text_composition:
    path: modules/text_composition
  audioplayers: ^0.18.3
  # audioplayers:
  #   path: modules/audioplayers
  flutter_qjs: ^0.3.6
  # flutter_js:
  #   path: modules/flutter_js
  flutter_webview:
    path: modules/flutter_webview
  webview_flutter:
    path: modules/webview_flutter
  windows_speak:
    path: modules/windows_speak
  xpath_parse:
    path: modules/xpath
  about: ^2.0.0
  archive: ^3.1.2
  battery: ^2.0.1
  cached_network_image: ^3.0.0
  device_info: ^2.0.0
  # dlna: ^0.0.5
  dlna:
    path: modules/DLNA-Dart
  encrypt: ^5.0.0
  equatable: ^2.0.0
  fast_gbk: ^0.1.2+1
  filesystem_picker: ^2.0.0-nullsafety.0
  floor: ^1.0.1
  flutter_colorpicker: ^0.4.0
  flutter_highlight: ^0.6.0
  share: ^2.0.1
  flutter_tts: ^3.0.0
  html: ^0.15.0
  http: ^0.13.1
  image_gallery_saver: ^1.6.8
  intl: ^0.17.0
  json_path: ^0.3.0
  matrix_gesture_detector: ^0.1.0
  oktoast: ^3.0.0
  outline_material_icons: ^0.1.1
  package_info_plus: ^1.0.0
  path_provider: ^2.0.1
  permission_handler: ^6.1.1
  photo_view: ^0.11.1
  provider: ^5.0.0
  screen: ^0.0.5
  scrollable_positioned_list: ^0.1.10
  shared_preferences: ^2.0.5
  sqflite_common_ffi: ^2.0.0
  url_launcher: ^6.0.3
  uuid: ^3.0.4
  video_player: ^2.1.1
  # webdav: ^1.0.8-dev
  webdav:
    git: https://github.com/timestee/dart-webdav

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.5
  floor_generator: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - CHANGELOG.md
    - README.md
    - LICENSE
    - lib/assets/
    - assets/JsDecoder.js
  fonts:
    - family: fonticons
      fonts:
        - asset: fonts/fonticons.ttf

    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900
