name: eso
description: 亦搜，亦看，亦闻
publish_to: none
version: 1.21.09+12109
homepage: https://github.com/mabdc/eso
author: mabdc

environment:
  sdk: ">=2.2.2 <3.2.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  text_composition:
    path: modules/text_composition
  audioplayers:
    path: modules/audioplayers
  flutter_qjs: ^0.3.5
  # flutter_js:
  #   path: modules/flutter_js
  flutter_webview:
    path: modules/flutter_webview
  webview_flutter:
    path: modules/webview_flutter
  windows_speak:
    path: modules/windows_speak
  xpath_parse:
    path: modules/xpath
  about: ^1.4.0
  archive: ^2.0.13
  battery: ^2.0.0
  cached_network_image: ^2.3.3
  cupertino_icons: ^1.0.2
  device_info: ^2.0.0
  dlna: ^0.0.5
  encrypt: ^4.1.0
  equatable: ^1.2.6
  fast_gbk: ^0.1.2+1
  file_chooser: ^0.1.6
  file_picker: ^2.1.6
  floor: ^0.19.1
  flutter_colorpicker: ^0.3.5
  flutter_share: ^1.0.5
  flutter_slidable: ^0.5.7
  flutter_tts: ^2.1.0
  html: ^0.14.0+4
  http: ^0.12.2
  image_gallery_saver: ^1.6.8
  intl: ^0.17.0
  json_path: ^0.2.1
  matrix_gesture_detector: ^0.1.0
  oktoast: ^3.0.0
  outline_material_icons: ^0.1.1
  package_info_plus: ^0.6.4
  path_provider: ^1.6.27
  permission_handler: ^5.1.0+2
  photo_view: ^0.10.3
  provider: ^4.3.3
  screen: ^0.0.5
  scrollable_positioned_list: ^0.1.10
  shared_preferences: ^0.5.12+4
  sqflite_common_ffi: ^1.1.1+3
  url_launcher: ^5.7.10
  uuid: ^2.2.2
  video_player: ^2.0.0
  webdav: ^1.0.8-dev

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.5
  floor_generator: ^0.19.1

flutter:
  uses-material-design: true
  assets:
    - CHANGELOG.md
    - README.md
    - LICENSE
    - lib/assets/
  fonts:
    - family: fonticons
      fonts:
        - asset: fonts/fonticons.ttf

    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900
