name: eso
description: 亦搜，亦看，亦闻

version: 1.12.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_seekbar:
    git: https://github.com/LiuC520/flutter_seekbar.git
  cupertino_icons: ^0.1.3
  provider: ^4.0.5
  shared_preferences: ^0.5.6+3
  http: ^0.12.0+4
  equatable: ^1.1.1
  url_launcher: ^5.4.2
  fast_gbk: ^0.1.2+1
  flutter_share: ^1.0.2+1
  crypto: ^2.1.3
  html:
    git:
      url: https://github.com/chen-zeyu/html.git
      ref: patch-pola
  intl: ^0.15.7
  device_info: ^0.4.0
  flutter_screenutil: ^1.0.2
  matrix_gesture_detector: ^0.1.0
  flutter_slidable: ^0.5.4
  # wakelock: ^0.1.3
  video_player:
    git: 
      url: https://github.com/cbenhagen/plugins.git
      ref: video_player_macos
      path: packages/video_player/video_player
  path_provider: ^1.6.5
  audioplayers: ^0.15.1
  encrypt: ^4.0.0
  archive: ^2.0.11
  webview_flutter: 0.3.15+1
  battery: 0.3.1+10
  flutter_js: 
    path: modules/flutter_js
    # git: https://github.com/abner/flutter_js
  jsonpath: 
    path: modules/jsonpath
    # https://github.com/qhzhyt/dart-json-path.git
  uuid: ^2.0.4
  floor: ^0.12.0
  toast: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  # floor_generator: ^0.12.0
  # build_runner: ^1.7.3

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
